/**
 * Created by Mr.W on 2016/10/10.
 */
var cityDate = [
    {
        value:100,
        name:'北京市',
        children:[{
                value:1001,
                name:'北京市',
                children:[
                    {value:10011,name:'朝阳区'},
                    {value:10012,name:'东城区'},
                    {value:10013,name:'西城区'},
                    {value:10014,name:'昌平区'},
                    {value:10015,name:'海淀区'},
                    {value:10016,name:'通州区'}
                ]}
        ]
    },
    {
        value:101,
        name:'山东省',
        children:[{
                value:1011,
                name:'济南市',
                children:[
                    {value:10111,name:'历下区'},
                    {value:10112,name:'aa区'},
                    {value:10113,name:'bb区'},
                    {value:10114,name:'cc区'},
                    {value:10115,name:'dd区'},
                    {value:10116,name:'ee区'}
                ]},
            {
                value:1012,
                name:'青岛市',
                children:[
                    {value:10121,name:'市南区'},
                    {value:10122,name:'市北区'},
                    {value:10123,name:'李沧区'},
                    {value:10124,name:'崂山区'},
                    {value:10125,name:'城阳区'},
                    {value:10126,name:'胶州区'}
                ]
            },
        ]
    },
    {
        value:102,
        name:'山西省',
        children:[{
                value:1021,
                name:'太原市',
                children:[
                    {value:10211,name:'1区'},
                    {value:10212,name:'2区'},
                    {value:10213,name:'3区'},
                    {value:10214,name:'4区'},
                    {value:10215,name:'5区'},
                    {value:10216,name:'6区'}
                ]},
            {
                value:1022,
                name:'大同市',
                children:[
                    {value:10221,name:'6区'},
                    {value:10222,name:'5区'},
                    {value:10223,name:'4区'},
                    {value:10224,name:'3区'},
                    {value:10225,name:'2区'},
                    {value:10226,name:'1区'}
                ]
            },
        ]
    },
]